Started logging messages at Fri Apr 30 13:59:31 2021
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 45 B-reps in file
Info:    Found 45 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 68
Info:            Created 
Info:        Working on 70
Info:            Created 
Info:        Working on 72
Info:            Created 
Info:        Working on 74
Info:            Created 
Info:        Working on 49
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 2.87393e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 1
Info:        Working on 98
Info:            Created 
Info:        Working on 100
Info:            Created 
Info:        Working on 102
Info:            Created 
Info:        Working on 104
Info:            Created 
Info:        Working on 79
Info:            Created 
Info:        Created 
Info:    Working on BRep 1
Info:        Using 3D tolerance 2.87393e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 2
Info:        Working on 128
Info:            Created 
Info:        Working on 130
Info:            Created 
Info:        Working on 132
Info:            Created 
Info:        Working on 134
Info:            Created 
Info:        Working on 109
Info:            Created 
Info:        Created 
Info:    Working on BRep 2
Info:        Using 3D tolerance 3.40099e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 3
Info:        Working on 162
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 160
Info:            Created 
Info:        Working on 158
Info:            Created 
Info:        Working on 139
Info:            Created 
Info:        Created 
Info:    Working on BRep 3
Info:        Using 3D tolerance 3.55041e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 4
Info:        Working on 188
Info:            Created 
Info:        Working on 190
Info:            Created 
Info:        Working on 194
Info:            Created 
Info:        Working on 192
Info:            Created 
Info:        Working on 169
Info:            Created 
Info:        Created 
Info:    Working on BRep 4
Info:        Using 3D tolerance 3.37921e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 5
Info:        Working on 222
Info:            Created 
Info:        Working on 224
Info:            Created 
Info:        Working on 218
Info:            Created 
Info:        Working on 220
Info:            Created 
Info:        Working on 199
Info:            Created 
Info:        Created 
Info:    Working on BRep 5
Info:        Using 3D tolerance 2.04922e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 6
Info:        Working on 248
Info:            Created 
Info:        Working on 250
Info:            Created 
Info:        Working on 252
Info:            Created 
Info:        Working on 254
Info:            Created 
Info:        Working on 229
Info:            Created 
Info:        Created 
Info:    Working on BRep 6
Info:        Using 3D tolerance 3.37921e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 7
Info:        Working on 282
Info:            Created 
Info:        Working on 284
Info:            Created 
Info:        Working on 280
Info:            Created 
Info:        Working on 278
Info:            Created 
Info:        Working on 259
Info:            Created 
Info:        Created 
Info:    Working on BRep 7
Info:        Using 3D tolerance 3.47617e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 8
Info:        Working on 308
Info:            Created 
Info:        Working on 310
Info:            Created 
Info:        Working on 312
Info:            Created 
Info:        Working on 314
Info:            Created 
Info:        Working on 289
Info:            Created 
Info:        Created 
Info:    Working on BRep 8
Info:        Using 3D tolerance 3.96273e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 9
Info:        Working on 374
Info:            Created 
Info:        Working on 376
Info:            Created 
Info:        Working on 372
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 378
Info:            Created 
Info:        Working on 380
Info:            Created 
Info:        Working on 382
Info:            Created 
Info:        Working on 384
Info:            Created 
Info:        Working on 386
Info:            Created 
Info:        Working on 388
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 392
Info:            Created 
Info:        Working on 319
Info:            Created 
Info:        Created 
Info:    Working on BRep 9
Info:        Using 3D tolerance 4.55668e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 10
Info:        Working on 448
Info:            Created 
Info:        Working on 470
Info:            Created 
Info:        Working on 468
Info:            Created 
Info:        Working on 466
Info:            Created 
Info:        Working on 464
Info:            Created 
Info:        Working on 462
Info:            Created 
Info:        Working on 460
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 456
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Working on 452
Info:            Created 
Info:        Working on 450
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Created 
Info:    Working on BRep 10
Info:        Using 3D tolerance 2.18149e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 11
Info:        Working on 492
Info:            Created 
Info:        Working on 494
Info:            Created 
Info:        Working on 490
Info:            Created 
Info:        Working on 475
Info:            Created 
Info:        Created 
Info:    Working on BRep 11
Info:        Using 3D tolerance 1.52122e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 12
Info:        Working on 510
Info:            Created 
Info:        Working on 512
Info:            Created 
Info:        Working on 499
Info:            Created 
Info:        Created 
Info:    Working on BRep 12
Info:        Using 3D tolerance 3.60771e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 13
Info:        Working on 538
Info:            Created 
Info:        Working on 540
Info:            Created 
Info:        Working on 536
Info:            Created 
Info:        Working on 542
Info:            Created 
Info:        Working on 517
Info:            Created 
Info:        Created 
Info:    Working on BRep 13
Info:        Using 3D tolerance 3.40099e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 14
Info:        Working on 572
Info:            Created 
Info:        Working on 568
Info:            Created 
Info:        Working on 570
Info:            Created 
Info:        Working on 566
Info:            Created 
Info:        Working on 547
Info:            Created 
Info:        Created 
Info:    Working on BRep 14
Info:        Using 3D tolerance 3.55041e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 15
Info:        Working on 598
Info:            Created 
Info:        Working on 602
Info:            Created 
Info:        Working on 596
Info:            Created 
Info:        Working on 600
Info:            Created 
Info:        Working on 577
Info:            Created 
Info:        Created 
Info:    Working on BRep 15
Info:        Using 3D tolerance 3.37921e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 16
Info:        Working on 628
Info:            Created 
Info:        Working on 630
Info:            Created 
Info:        Working on 626
Info:            Created 
Info:        Working on 632
Info:            Created 
Info:        Working on 607
Info:            Created 
Info:        Created 
Info:    Working on BRep 16
Info:        Using 3D tolerance 2.87393e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 17
Info:        Working on 662
Info:            Created 
Info:        Working on 656
Info:            Created 
Info:        Working on 660
Info:            Created 
Info:        Working on 658
Info:            Created 
Info:        Working on 637
Info:            Created 
Info:        Created 
Info:    Working on BRep 17
Info:        Using 3D tolerance 2.04922e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 18
Info:        Working on 688
Info:            Created 
Info:        Working on 690
Info:            Created 
Info:        Working on 686
Info:            Created 
Info:        Working on 692
Info:            Created 
Info:        Working on 667
Info:            Created 
Info:        Created 
Info:    Working on BRep 18
Info:        Using 3D tolerance 2.87393e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 19
Info:        Working on 718
Info:            Created 
Info:        Working on 720
Info:            Created 
Info:        Working on 716
Info:            Created 
Info:        Working on 722
Info:            Created 
Info:        Working on 697
Info:            Created 
Info:        Created 
Info:    Working on BRep 19
Info:        Using 3D tolerance 3.37921e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 20
Info:        Working on 752
Info:            Created 
Info:        Working on 748
Info:            Created 
Info:        Working on 750
Info:            Created 
Info:        Working on 746
Info:            Created 
Info:        Working on 727
Info:            Created 
Info:        Created 
Info:    Working on BRep 20
Info:        Using 3D tolerance 3.47617e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 21
Info:        Working on 776
Info:            Created 
Info:        Working on 780
Info:            Created 
Info:        Working on 778
Info:            Created 
Info:        Working on 782
Info:            Created 
Info:        Working on 757
Info:            Created 
Info:        Created 
Info:    Working on BRep 21
Info:        Using 3D tolerance 3.96273e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 22
Info:        Working on 842
Info:            Created 
Info:        Working on 840
Info:            Created 
Info:        Working on 846
Info:            Created 
Info:        Working on 848
Info:            Created 
Info:        Working on 850
Info:            Created 
Info:        Working on 852
Info:            Created 
Info:        Working on 854
Info:            Created 
Info:        Working on 856
Info:            Created 
Info:        Working on 858
Info:            Created 
Info:        Working on 860
Info:            Created 
Info:        Working on 844
Info:            Created 
Info:        Working on 838
Info:            Created 
Info:        Working on 787
Info:            Created 
Info:        Created 
Info:    Working on BRep 22
Info:        Using 3D tolerance 4.55668e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 23
Info:        Working on 890
Info:            Created 
Info:        Working on 888
Info:            Created 
Info:        Working on 896
Info:            Created 
Info:        Working on 894
Info:            Created 
Info:        Working on 892
Info:            Created 
Info:        Working on 865
Info:            Created 
Info:        Created 
Info:    Working on BRep 23
Info:        Using 3D tolerance 1.47376e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 24
Info:        Working on 920
Info:            Created 
Info:        Working on 924
Info:            Created 
Info:        Working on 926
Info:            Created 
Info:        Working on 922
Info:            Created 
Info:        Working on 901
Info:            Created 
Info:        Created 
Info:    Working on BRep 24
Info:        Using 3D tolerance 2.18271e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 25
Info:        Working on 954
Info:            Created 
Info:        Working on 962
Info:            Created 
Info:        Working on 956
Info:            Created 
Info:        Working on 960
Info:            Created 
Info:        Working on 958
Info:            Created 
Info:        Working on 931
Info:            Created 
Info:        Created 
Info:    Working on BRep 25
Info:        Using 3D tolerance 1.38865e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 26
Info:        Working on 988
Info:            Created 
Info:        Working on 986
Info:            Created 
Info:        Working on 992
Info:            Created 
Info:        Working on 990
Info:            Created 
Info:        Working on 967
Info:            Created 
Info:        Created 
Info:    Working on BRep 26
Info:        Using 3D tolerance 1.32197e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 27
Info:        Working on 1022
Info:            Created 
Info:        Working on 1020
Info:            Created 
Info:        Working on 1028
Info:            Created 
Info:        Working on 1026
Info:            Created 
Info:        Working on 1024
Info:            Created 
Info:        Working on 997
Info:            Created 
Info:        Created 
Info:    Working on BRep 27
Info:        Using 3D tolerance 1.38865e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 28
Info:        Working on 1052
Info:            Created 
Info:        Working on 1056
Info:            Created 
Info:        Working on 1058
Info:            Created 
Info:        Working on 1054
Info:            Created 
Info:        Working on 1033
Info:            Created 
Info:        Created 
Info:    Working on BRep 28
Info:        Using 3D tolerance 2.21399e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 29
Info:        Working on 1086
Info:            Created 
Info:        Working on 1094
Info:            Created 
Info:        Working on 1088
Info:            Created 
Info:        Working on 1092
Info:            Created 
Info:        Working on 1090
Info:            Created 
Info:        Working on 1063
Info:            Created 
Info:        Created 
Info:    Working on BRep 29
Info:        Using 3D tolerance 1.47376e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 30
Info:        Working on 1136
Info:            Created 
Info:        Working on 1128
Info:            Created 
Info:        Working on 1126
Info:            Created 
Info:        Working on 1134
Info:            Created 
Info:        Working on 1130
Info:            Created 
Info:        Working on 1132
Info:            Created 
Info:        Working on 1099
Info:            Created 
Info:        Created 
Info:    Working on BRep 30
Info:        Using 3D tolerance 1.32201e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 31
Info:        Working on 1178
Info:            Created 
Info:        Working on 1172
Info:            Created 
Info:        Working on 1174
Info:            Created 
Info:        Working on 1176
Info:            Created 
Info:        Working on 1170
Info:            Created 
Info:        Working on 1168
Info:            Created 
Info:        Working on 1141
Info:            Created 
Info:        Created 
Info:    Working on BRep 31
Info:        Using 3D tolerance 1.32201e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 32
Info:        Working on 1206
Info:            Created 
Info:        Working on 1208
Info:            Created 
Info:        Working on 1210
Info:            Created 
Info:        Working on 1214
Info:            Created 
Info:        Working on 1212
Info:            Created 
Info:        Working on 1183
Info:            Created 
Info:        Created 
Info:    Working on BRep 32
Info:        Using 3D tolerance 1.47376e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 33
Info:        Working on 1238
Info:            Created 
Info:        Working on 1242
Info:            Created 
Info:        Working on 1244
Info:            Created 
Info:        Working on 1240
Info:            Created 
Info:        Working on 1219
Info:            Created 
Info:        Created 
Info:    Working on BRep 33
Info:        Using 3D tolerance 2.21399e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 34
Info:        Working on 1274
Info:            Created 
Info:        Working on 1278
Info:            Created 
Info:        Working on 1272
Info:            Created 
Info:        Working on 1276
Info:            Created 
Info:        Working on 1280
Info:            Created 
Info:        Working on 1249
Info:            Created 
Info:        Created 
Info:    Working on BRep 34
Info:        Using 3D tolerance 1.38865e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 35
Info:        Working on 1308
Info:            Created 
Info:        Working on 1310
Info:            Created 
Info:        Working on 1306
Info:            Created 
Info:        Working on 1304
Info:            Created 
Info:        Working on 1285
Info:            Created 
Info:        Created 
Info:    Working on BRep 35
Info:        Using 3D tolerance 1.32197e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 36
Info:        Working on 1338
Info:            Created 
Info:        Working on 1340
Info:            Created 
Info:        Working on 1342
Info:            Created 
Info:        Working on 1346
Info:            Created 
Info:        Working on 1344
Info:            Created 
Info:        Working on 1315
Info:            Created 
Info:        Created 
Info:    Working on BRep 36
Info:        Using 3D tolerance 1.38865e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 37
Info:        Working on 1370
Info:            Created 
Info:        Working on 1374
Info:            Created 
Info:        Working on 1376
Info:            Created 
Info:        Working on 1372
Info:            Created 
Info:        Working on 1351
Info:            Created 
Info:        Created 
Info:    Working on BRep 37
Info:        Using 3D tolerance 2.18271e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 38
Info:        Working on 1404
Info:            Created 
Info:        Working on 1408
Info:            Created 
Info:        Working on 1406
Info:            Created 
Info:        Working on 1410
Info:            Created 
Info:        Working on 1412
Info:            Created 
Info:        Working on 1381
Info:            Created 
Info:        Created 
Info:    Working on BRep 38
Info:        Using 3D tolerance 1.47376e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 39
Info:        Working on 1470
Info:            Created 
Info:        Working on 1476
Info:            Created 
Info:        Working on 1472
Info:            Created 
Info:        Working on 1474
Info:            Created 
Info:        Working on 1468
Info:            Created 
Info:        Working on 1478
Info:            Created 
Info:        Working on 1490
Info:            Created 
Info:        Working on 1488
Info:            Created 
Info:        Working on 1486
Info:            Created 
Info:        Working on 1482
Info:            Created 
Info:        Working on 1484
Info:            Created 
Info:        Working on 1480
Info:            Created 
Info:        Working on 1417
Info:            Created 
Info:        Created 
Info:    Working on BRep 39
Info:        Using 3D tolerance 2.18149e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 40
Info:        Working on 1518
Info:            Created 
Info:        Working on 1514
Info:            Created 
Info:        Working on 1516
Info:            Created 
Info:        Working on 1520
Info:            Created 
Info:        Working on 1495
Info:            Created 
Info:        Created 
Info:    Working on BRep 40
Info:        Using 3D tolerance 1.48171e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 41
Info:        Working on 1548
Info:            Created 
Info:        Working on 1544
Info:            Created 
Info:        Working on 1546
Info:            Created 
Info:        Working on 1550
Info:            Created 
Info:        Working on 1525
Info:            Created 
Info:        Created 
Info:    Working on BRep 41
Info:        Using 3D tolerance 1.48171e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 42
Info:        Working on 1574
Info:            Created 
Info:        Working on 1576
Info:            Created 
Info:        Working on 1580
Info:            Created 
Info:        Working on 1578
Info:            Created 
Info:        Working on 1555
Info:            Created 
Info:        Created 
Info:    Working on BRep 42
Info:        Using 3D tolerance 1.48171e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 43
Info:        Working on 1604
Info:            Created 
Info:        Working on 1606
Info:            Created 
Info:        Working on 1610
Info:            Created 
Info:        Working on 1608
Info:            Created 
Info:        Working on 1585
Info:            Created 
Info:        Created 
Info:    Working on BRep 43
Info:        Using 3D tolerance 1.48171e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 44
Info:        Working on 1634
Info:            Created 
Info:        Working on 1630
Info:            Created 
Info:        Working on 1632
Info:            Created 
Info:        Working on 1615
Info:            Created 
Info:        Created 
Info:    Working on BRep 44
Info:        Using 3D tolerance 1.52094e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                 45 found      45 created       0 failed
Finished logging messages at Fri Apr 30 13:59:32 2021
